server:
  port: 8084

spring:
  application:
    name: feign

eureka:
  instance:
    hostname: localhost
    #以IP地址注册到服务中心，相互注册使用IP地址
  #    prefer-ip-address: true

  client:
    service-url:
      #服务注册地址
      defaultZone: http://${eureka.instance.hostname}:8080/eureka

